### ISSUE TITLE
Ruby 3 compatibility

### ISSUE THREAD

**Issue by swiknaba** [WeTransfer/zip_tricks#104]
Currently, specs are failing under Ruby 3, see: https://github.com/WeTransfer/zip_tricks/pull/103

We should address these issues, i.e. update the syntax to be compatible with Ruby 3.

**Comment by julik** [comment]
I have merged #103 thank you for doing this work! We do not have ruby 3 in production anywhere so it is very valuable. Can you pick this up once `rspec-mocks` is updated?

**Comment by swiknaba** [comment]
rspec-mocks is updated now (details: https://github.com/rspec/rspec-mocks/issues/1396), basically we'll need to use `>= 3.10.2` for Ruby 3 compatibility.
