### ISSUE TITLE
Question: Is it possible to use zip_tricks with byte ranges to support download resuming?

### ISSUE THREAD

**Issue by JulieWinchester** [WeTransfer/zip_tricks#109]
Thanks for putting this gem out there, it's great!

I see from the readme it's possible to estimate the total size of ZIP, and therefore the `Content-Length` header can be set correctly. Would it be possible to use zip_tricks in conjunction with byte range serving so that if a user downloading a streaming ZIP had their connection interrupted, they would be able to resume the download? Or is that not feasible due to how the ZIPs are being constructed on the fly? Thanks!

**Comment by julik** [comment]
Hey! It is possible but you do need more than just zip_tricks to accomplish this. We use a combination of zip_tricks and https://github.com/WeTransfer/interval_response and we cache the generated chunks of the ZIP file (not the bodies of the files we stitch into the output) upfront. It is not instant but enables the functionality that you are after. You can check out this presentation too: https://speakerdeck.com/julik/streaming-large-files-with-ruby

**Comment by JulieWinchester** [comment]
I'm looping back to this 1.5 years later, but I wanted to say that @julik your response was immensely helpful and greatly appreciated, thanks very much! I'll go ahead and close this issue out.
