### ISSUE TITLE
Issues on Rails

### ISSUE THREAD

**Issue by gencer** [WeTransfer/zip_tricks#13]
When I use zip_tricks with Rails (v5.x) I have two problems.

1. Unlike **RackBody**, **RailsStreaming** does not support `Content-Length`. `Live` class silently overrides this header.
2. When Rails sample (at README) used and if any accelerator installed (Download managers) both browser and download accelerator download the body. Download accelerators should takeover the file and download, instead, it takeover plus browser itself download the file. Twice.

Is there anyway to make it work in Rails and set the `content-length` properly?

Even If I decide to get over it about content length, still 2nd issue is important.

**Comment by gencer** [comment]
I solved content-length via Stream output (`fake_io`). But still, browser does download the file (not as an attachment as an inline like opening a html page) while download accelerator program download the file.

**Comment by julik** [comment]
❤️  thanks for investigating
