### ISSUE TITLE
Adopt Rubocop rules, investigate CI-based linting

### ISSUE THREAD

**Issue by julik** [WeTransfer/zip_tricks#15]
It would be nice if we could have a set of Rubocop rules and enforce them automatically on CI. The only file that I would rather omit from Rubocop is zip_writer.rb which is basically line-for-line the ZIP spec, so it's formatted in a particular way which I would like to leave intact.

We should look at Rubocop-hosting options (like codeclimate and/or Hound), but I've heard that Hound posts comments "per violation" instead of presenting a separate page with all the violations in one place - that might be too much line noise.

**Comment by bermannoah** [comment]
Closed in #17. So glad we didn't use Hound. Hound is a nightmare for exactly the reason you mention, @julik.
