### ISSUE TITLE
Specify modification date when adding entries to the Streamer

### ISSUE THREAD

**Issue by RTrampov** [WeTransfer/zip_tricks#41]
As I mentioned in #40 we had another requirement for which there was no readily available solution.

We save file modification dates in the database and wanted to preserve them when archiving files, so the modification date is the same in the archive as it is on the server. Here's an example:
```ruby
ZipTricks::Streamer.open(output_stream) do |streamer|
  streamer.write_stored_file('text-file.txt', modification_date: Time.now.utc) do |entry|
    # ...
  end
  streamer.write_deflated_file('picture.png', modification_date: Time.now.utc) do |entry|
    # ...
  end
end
```

Again - if you are interested in this I can try and open a pull request.

**Comment by julik** [comment]
Thanks for the proposal! 

Yes, that could clearly be useful. Since we already set creation/modification time extra fields for all entries output, would it be useful to set the creation time/access times as well?

**Comment by RTrampov** [comment]
Well our requirement is for modification time only but I guess create/access time could be useful to someone else.

That would require modification of `ZipTricks::ZipWriter#timestamp_extra` right? As it currently only accepts and sets the modification time?

**Comment by julik** [comment]
Correct. And we will need to add an argument to all the related methods (in Streamer and Writer)

**Comment by RTrampov** [comment]
For the time being I can open a PR about the modification time as it requires less amount of changes and maybe add create/access time later when I have the time?

**Comment by julik** [comment]
Yep, go for it!

**Comment by julik** [comment]
Fixed anf merged, thanks again!
