### ISSUE TITLE
Allow Streamer options to be passed to `zip_tricks_stream`

### ISSUE THREAD

**Issue by njakobsen** [WeTransfer/zip_tricks#68]
Specifically, I would like to enable `auto_rename_duplicate_filenames` in my Rails controller `zip_tricks_stream`.

```ruby
zip_tricks_stream(auto_rename_duplicate_filenames: true) do |zip|
  #...
end
```

This should be fairly straightforward as the arguments just need to be passed to the streamer here https://github.com/WeTransfer/zip_tricks/blob/c20dc8e2e502aa9375e892b270cddd86eefef555/lib/zip_tricks/rails_streaming.rb#L10-L18

**Comment by julik** [comment]
Good suggestion! Don't know when we could get to it - if you open a PR will gladly accept
