### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by WJWH** [WeTransfer/zip_tricks#77]
In the section "Send a ZIP from a Rack response" from the README it uses `{'Transfer-Encoding' => 'chunked'}` as the headers. This does not work in at least Puma, Unicorn and Thin (and possibly more but I haven't tried).

Minimal reproduction `.ru` file to reproduce (assuming you have `gem install`ed a server)
```ruby
# broken_ziptricks_example.ru
require 'zip_tricks'

app = ->(env) {
  body = ZipTricks::RackBody.new do | zip |
    zip.write_stored_file('broken_ziptricks_example.ru') do |sink|
      File.open('broken_ziptricks_example.ru', 'rb'){|source| IO.copy_stream(source, sink) }
    end
  end
  [200, {'Transfer-Encoding' => 'chunked'}, body]
}

run app
``` 
Hitting this with `curl` will show what is wrong: 
```
* Illegal or missing hexadecimal sequence in chunked-encoding
* Closing connection 0
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```
Puma, Thin and Unicorn assume that if you set `{'Transfer-Encoding' => 'chunked'}`, you will be responsible for the actual chunk encoding yourself; ie prefixing with the chunk length etc. `ZipTricks::RackBody` does not do this. However, if you remove `{'Transfer-Encoding' => 'chunked'}` from the headers it works again as the servers take care of this for you.

**Comment by julik** [comment]
Thanks for the find 🙏
